language: node_js
node_js:
  - "node"
install:
  - yarn install
cache:
  directories:
  - node_modules
  - packages/create-react-app/node_modules
  - packages/react-scripts/node_modules
script:
  - yarn test
after_success:
  - yarn report-coverage
